apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-api-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "python-api-service.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "python-api-service.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "python-api-service.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
