apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-api-service.fullname" . }}
  labels:
    {{- include "python-api-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "python-api-service.labels" . | nindent 4 }}
  ports:
    - name: {{ .Values.metrics.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
