apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "python-api-service.fullname" . }}-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      {{ include "python-api-service.labels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: {{ .Values.metrics.portName }}
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.interval }}
