name: ""
replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: Always

containerPort: 8000

service:
  type: LoadBalancer
  port: 8000

metrics:
  enabled: true
  path: /metrics
  interval: 15s
  portName: http

namespace: default
